import Head from "next/head"
import { Container, Divider, Stack } from "@chakra-ui/react"
import { useState, useEffect } from "react"

import Header from "../components/explore/header"
import QueryCard from "../components/explore/queryCard"
import { QueryData } from "../types"
import { getQueryData } from "../firebase/queryData"

export default function Explor() {
  const [queryList, setQueryList] = useState<QueryData[] | undefined>([])

  useEffect(() => {
    const getData = async () => {
      const data = await getQueryData()
      setQueryList(data)
    }

    getData()
  }, [])

  return (
    <div>
      <Head>
        <title>Flex Node - Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        minWidth="100vw"
        display="flex"
        alignItems="center"
        flexDirection="column"
      >
        <Header />
        <Divider width="80%" my="5" />
        <Stack width="80%">
          <QueryCard />
          <QueryCard />
        </Stack>
      </Container>
    </div>
  )
}
