import Head from "next/head"
import {
  Box,
  Container,
  Flex,
  Input,
  InputGroup,
  InputLeftElement,
  Skeleton,
  SkeletonCircle,
  Stack,
  VStack,
} from "@chakra-ui/react"
import { useState, useEffect } from "react"

import Header from "../components/explore/header"
import QueryCard from "../components/explore/queryCard"
import { QueryData } from "../types"
import { getQueryData } from "../firebase/queryData"
import { SearchIcon } from "@chakra-ui/icons"

export default function Explor() {
  const [queryList, setQueryList] = useState<QueryData[] | undefined>([])
  const [isLoading, setIsLoading] = useState<boolean>(false)
  const [search, setSearch] = useState<string>("")

  useEffect(() => {
    setIsLoading(true)
    const getData = async () => {
      const data = await getQueryData()
      console.log(data)

      setQueryList(data)
      setIsLoading(false)
    }

    getData()
  }, [])

  return (
    <div>
      <Head>
        <title>Flex Node - Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        minWidth="100vw"
        minHeight="80vh"
        display="flex"
        alignItems="center"
        flexDirection="column"
      >
        <Header />
        <InputGroup variant="flushed" width="80%" my="5" alignItems="center">
          <SearchIcon color="gray.300" mx="5" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            type="text"
            placeholder="Search"
          />
        </InputGroup>
        <Flex width="80%" display="flex" flexWrap="wrap" gap="4">
          {queryList &&
            queryList
              .filter((data) => data.queryName.indexOf(search) > -1)
              .map((data, index) => <QueryCard key={index} data={data} />)}

          {isLoading &&
            Array(10)
              .fill(0)
              .map((_, index) => (
                <Box
                  borderWidth="1px"
                  borderRadius="lg"
                  width="xl"
                  padding="6"
                  key={index}
                >
                  <Flex justify="space-between" align="center" gap="2">
                    <Flex gap="2" width="30%">
                      <SkeletonCircle size="16" />
                    </Flex>
                    <VStack align="left" justify="center" width="70%">
                      <Skeleton height="20px" />
                      <Skeleton height="20px" />
                    </VStack>
                  </Flex>
                </Box>
              ))}
        </Flex>
      </Container>
    </div>
  )
}
