import Head from "next/head"
import { CodeBlock, dracula } from "react-code-blocks"
import {
  Container,
  Divider,
  Flex,
  Link,
  ListItem,
  OrderedList,
  Text,
  UnorderedList,
  VStack,
} from "@chakra-ui/react"

import Header from "../components/guide/header"
import { ExternalLinkIcon } from "@chakra-ui/icons"

export default function Explor() {
  return (
    <div>
      <Head>
        <title>Flex Node - Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mini-logo.svg" />
      </Head>
      <Container
        minWidth="100vw"
        minHeight="80vh"
        display="flex"
        alignItems="center"
        flexDirection="column"
      >
        <Header />
        <Divider width="80%" my="5" />
        <VStack align="start" width="80%">
          <Text fontWeight="bold">Polygon Mumbai Testnet</Text>
          <UnorderedList>
            <ListItem>
              Link Token Contract: 0x326C977E6efc84E512bB9C30f76E30c160eD06FB
            </ListItem>
            <ListItem>
              Oracle Contract: 0x364AAB5aBd6C0B42f9Ba347dF024B67Cc6a4a882
            </ListItem>
            <ListItem>
              Get Flex Job Id: 98c356d16abe49e4939846ee6c52a364
            </ListItem>
            <ListItem>
              Get Field String Job Id: 542864ff9a6145b8bdcd733a9503ae09
            </ListItem>
            <ListItem>
              Get Field Uint Job Id: 70dd3b366b29405985a38469be42b9bb
            </ListItem>
          </UnorderedList>
        </VStack>
        <Divider my="10" width="50%" />
        <VStack align="start" width="80%">
          <Text fontWeight="bold">Query Creator</Text>
          <OrderedList>
            <ListItem>
              Go to{" "}
              <Link href="/create" target="_blank">
                Create <ExternalLinkIcon mx="2px" mb="1" />
              </Link>{" "}
              tab
            </ListItem>
            <ListItem>
              Fill information{" "}
              <UnorderedList>
                <ListItem>
                  <b>Query Name : </b>
                  Name of query that show on website
                </ListItem>
                <ListItem>
                  <b>Description : </b>
                  More information about the query
                </ListItem>
                <ListItem>
                  <b>Category : </b>
                  Category of query
                </ListItem>
                <ListItem>
                  <b>Protocol Chain : </b>
                  Chain of query protocol
                </ListItem>
                <ListItem>
                  <b>Protocol Name : </b>
                  Name of query protocol
                </ListItem>
                <ListItem>
                  <b>Endpoint : </b>
                  protocol graphql endpoint will call in chainlink external
                  adapter
                </ListItem>
                <ListItem>
                  <b>Query Command : </b>
                  Graphql command will parse into chainlink external adapter{" "}
                  <Text as="i">
                    ** This version we only support 1 variable named account **
                  </Text>
                </ListItem>
              </UnorderedList>
            </ListItem>
            <ListItem>Click Create button</ListItem>
            <ListItem>
              Query information will upload to ipfs and show on explore page
            </ListItem>
          </OrderedList>
          {/* <Text fontWeight="bold">
            Query information will upload to ipfs and show on explore page
          </Text> */}
        </VStack>
        <Divider my="10" width="50%" />
        <VStack align="start" width="80%">
          <Text fontWeight="bold">Developer</Text>
          <OrderedList>
            <ListItem>
              Inherit{" "}
              <Link
                href="https://github.com/tesol2y090/flex-node/blob/main/flex-contracts/src/FlexClient.sol"
                target="_blank"
                isExternal
              >
                FlexClient Contract <ExternalLinkIcon mx="2px" mb="1" />
              </Link>{" "}
              into your contract.
            </ListItem>
            <ListItem>
              Pass initial parameters to FlexClient constructor
              <UnorderedList>
                <ListItem>
                  <b>Link Token Contract</b>
                </ListItem>
                <ListItem>
                  <b>Oracle Contract</b>
                </ListItem>
                <ListItem>
                  <b>Get Flex Job Id</b>
                </ListItem>
                <ListItem>
                  <b>Get Field Job Id</b>
                </ListItem>
                <ListItem>
                  <b>CID : </b>
                  You can go to explore page to copy CID or create a new one.
                </ListItem>
              </UnorderedList>
            </ListItem>
            <ListItem>
              Call requestFlex to get data as CID
              <Container padding="0" my="2">
                <CodeBlock
                  text="requestFlex(string memory _cid, string memory _account)"
                  language="js"
                  theme={dracula}
                  showLineNumbers={false}
                />
              </Container>
            </ListItem>
            <ListItem>
              Chainlink will fullfill CID the result into
              <Container padding="0" my="2">
                <CodeBlock
                  text="mapping(string => string) public accountToCID;"
                  language="js"
                  theme={dracula}
                  showLineNumbers={false}
                />
              </Container>
            </ListItem>
            <ListItem>
              Call requestField to get data depending on path
              <Container padding="0" my="2">
                <CodeBlock
                  text="requestField(string memory _path, string memory _account)"
                  language="js"
                  theme={dracula}
                  showLineNumbers={false}
                />
              </Container>
            </ListItem>
            <ListItem>
              Chainlink will fullfill data the result into
              <Container padding="0" my="2">
                <CodeBlock
                  text="mapping(string => string) public accountToData;"
                  language="js"
                  theme={dracula}
                  showLineNumbers={false}
                />
              </Container>
            </ListItem>
            <ListItem>
              You can look at{" "}
              <Link
                href="https://github.com/tesol2y090/flex-node/blob/main/flex-contracts/src/Sample.sol"
                target="_blank"
                isExternal
              >
                Sample.sol <ExternalLinkIcon mx="2px" mb="1" />
              </Link>{" "}
            </ListItem>
          </OrderedList>
          {/* <Text fontWeight="bold">
            Query information will upload to ipfs and show on explore page
          </Text> */}
        </VStack>
      </Container>
    </div>
  )
}
