import Head from "next/head"
import Jumbotron from "../components/landing/Jumbotron"
import HowItWork from "../components/landing/HowItWork"
import ReadyBuilt from "../components/landing/ReadyBuilt"

export default function Home() {
  return (
    <>
      <Head>
        <title>Flex Node</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Jumbotron />
      <HowItWork />
      <ReadyBuilt />
    </>
  )
}
