import Head from "next/head"
import { useRouter } from "next/router"
import {
  Container,
  Divider,
  Stack,
  Link,
  FormControl,
  FormLabel,
  Textarea,
  Text,
  useToast,
} from "@chakra-ui/react"
import Header from "../../components/query/header"
import { useState, useEffect } from "react"
import { decode } from "js-base64"
import { getQueryDataOne } from "../../firebase/queryData"
import { ExternalLinkIcon, CopyIcon } from "@chakra-ui/icons"
import { CodeBlock, github } from "react-code-blocks"

export default function Create() {
  const toast = useToast()
  const router = useRouter()
  const { query: queryRouter } = router
  const { id: queryId } = queryRouter

  const [name, setName] = useState<string | undefined>("")
  const [description, setDescription] = useState<string | undefined>("")
  const [chain, setChain] = useState<string | undefined>("")
  const [category, setCategory] = useState<string | undefined>("")
  const [endpoint, setEndpoint] = useState<string | undefined>("")
  const [cid, setCid] = useState<string | undefined>("")
  const [query, setQuery] = useState<string | undefined>("")
  const [creator, setCreator] = useState<string | undefined>("")
  const [protocol, setProtocol] = useState<string | undefined>("")

  useEffect(() => {
    if (!queryId) return
    const getData = async () => {
      const queryData = await getQueryDataOne(queryId)
      setName(queryData?.queryName)
      setDescription(queryData?.description)
      setChain(queryData?.protocolChain)
      setProtocol(queryData?.protocolName)
      setCategory(queryData?.category)
      setEndpoint(queryData?.endpoint)
      setQuery(decode(queryData?.query || ""))
      setCreator(queryData?.creator)
      setCid(queryData?.cid)
    }

    getData()
  }, [queryId])

  return (
    <div>
      <Head>
        <title>Flex Node - Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mini-logo.svg" />
      </Head>
      <Container
        minWidth="100vw"
        display="flex"
        alignItems="center"
        flexDirection="column"
      >
        <Header name={name} chain={chain} />
        <Divider width="80%" my="5" />
        <Stack width="80%" gap="2">
          <FormControl>
            <FormLabel fontWeight="bold">Description</FormLabel>
            <Text> - {description}</Text>
          </FormControl>
          <FormControl>
            <FormLabel fontWeight="bold">Protocol</FormLabel>
            <Text> - {protocol}</Text>
          </FormControl>
          <FormControl>
            <FormLabel fontWeight="bold">Chain</FormLabel>
            <Text> - {chain}</Text>
          </FormControl>
          <FormControl>
            <FormLabel fontWeight="bold">Category</FormLabel>
            <Text> - {category}</Text>
          </FormControl>
          <FormControl>
            <FormLabel fontWeight="bold">Endpoint</FormLabel>
            <Text>
              -{" "}
              <Link href={endpoint} isExternal>
                {endpoint} <ExternalLinkIcon mx="2px" />
              </Link>
            </Text>
          </FormControl>
          <FormControl>
            <FormLabel fontWeight="bold">CID</FormLabel>
            <Text>
              -{" "}
              <Link href={`https://${cid}.ipfs.w3s.link/`} isExternal>
                {cid}
              </Link>
              <CopyIcon
                mx="2"
                cursor="pointer"
                onClick={() => {
                  navigator.clipboard.writeText(cid || "")
                  toast({
                    title: `CID copied to clipboard`,
                    status: "success",
                    isClosable: true,
                    position: "bottom",
                  })
                }}
              />
            </Text>
          </FormControl>
          <FormControl>
            <FormLabel fontWeight="bold">Query Command</FormLabel>
            <CodeBlock
              style={{ width: "100%" }}
              text={query}
              language="graphql"
              theme={github}
              showLineNumbers={false}
              codeBlock={true}
            />
          </FormControl>
          <FormControl>
            <FormLabel fontWeight="bold">Creator</FormLabel>
            <Text> - {creator}</Text>
          </FormControl>
        </Stack>
      </Container>
    </div>
  )
}
